// <auto-generated/>
namespace LinkGate.frontend.Pages
{
    public partial class Counter
    {

        private int currentCount = 0;

        private void IncrementCount()
        {
            currentCount+=4;
        }
    }
}
